name: secretSanta-CI

on:
   push:
     branches: [main]
     paths-ignore:
      - '*.md'
      - 'README*'
      - 'LICENSE'

   pull_request:
     branches: [main]
     paths-ignore:
      - '*.md'
      - 'README*'
      - 'LICENSE'

jobs:
  Lint:
    name: Lint (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        os: ['ubuntu-latest']
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          pip install black
          pip install isort
          pip install codespell
      - name: Formatting and sorting import
        run: |
          source .github/linters/formatting.sh
          format . true
  Test:
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        os: ['ubuntu-latest', 'macos-latest']
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install package
        run: |
          pip install .
      - name: Tests
        run: |
          python -m pip install pytest
          cd tests
          pytest -v -s --disable-warnings
